# Usage: ansible-playbook playbook.yaml
---
- name: Provision Kubernetes on host
  hosts: all
  gather_facts: false  
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
