# Usage: ansible-playbook playbook.yaml
---
- name: Provision Kubernetes on host
  hosts: all
  gather_facts: false  
  become: true

  tasks:
  - name: Install apt packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - snapd

  - name: Install MicroK8S
    command: snap install microk8s --classic
    args:
      creates: /snap/bin/microk8s.kubectl

